language: go
sudo: required

go:
  - 1.12.1

node_js:
  - 10.13.0

os:
  - windows

env:
  global:
    - GO111MODULE=on

    # user defined

    # artefacts
    - ARTEFACTS_ZIP_URL=http://artdev.privatix.net/artefacts_win.zip

    #bitrock
    - BITROCK_VERSION=19.5.0

    # windows
    - BITROCK_INSTALLER_WIN=$HOME/installbuilder-${BITROCK_VERSION}
    - BITROCK_INSTALLER_BIN_WIN=${BITROCK_INSTALLER_WIN}\bin

#cache: npm
cache:
  directories:
    - $HOME\AppData\Local\go-build
    - $HOME\go\pkg\mod

git:
  depth: 1



before_install:
#- powershell.exe -command "write-host asadda"
- PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted'
- PowerShell -File 'c:\Users\Travis\Privatix\privatix\travis\win\before_install.ps1'

install:
- powershell.exe -File c:\\Users\\Travis\\Privatix\\privatix\\travis\\win\\install.ps1

before_script:
- . ${TRAVIS_BUILD_DIR}/travis/win/before_script.sh

script:
- powershell.exe -File c:\\Users\\Travis\\Privatix\\privatix\\travis\\win\\script.ps1

after_success:
- . ${TRAVIS_BUILD_DIR}/travis/win/after_success.sh

deploy:

notifications:
  email: false

#notifications:
#    slack:
#        rooms:
#            - privatix:ntmw2wh4PAHoodqtMc95KFDt#dapp-tech
