language: go
sudo: required

go:
  - 1.12.1

node_js:
  - 10.13.0

os: linux
dist: xenial

env:
  global:

git:
  depth: 1

git:
  depth: 1

before_install:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e ">>> some magic"
  - echo -n $autotest1 > /tmp/travis_rsa_tests
  - base64 --decode /tmp/travis_rsa_tests > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - mv -fv ./travis/atests/ssh-config ~/.ssh/config
  - ssh -i ~/.ssh/id_rsa stagevm@89.38.99.85
  



