language: go
sudo: required

go:
  - 1.12.1

node_js:
  - 10.13.0

os:
#  - linux
  - osx
#

env:
  global:
    - GO111MODULE=on

    # user defined

    # artefacts
    - ARTEFACTS_ZIP_URL=http://artdev.privatix.net/artefacts_mac.zip

    #bitrock
    - BITROCK_VERSION=19.5.0

    # linux
    - BITROCK_INSTALLER_LINUX=~/installbuilder-${BITROCK_VERSION}
    - BITROCK_INSTALLER_BIN_LINUX=${BITROCK_INSTALLER_LINUX}/bin

    # osx
    - BITROCK_INSTALLER_MAC="/Applications/BitRock InstallBuilder Enterprise ${BITROCK_VERSION}"
    - BITROCK_INSTALLER_BIN_MAC="${BITROCK_INSTALLER_MAC}/bin"

#cache: npm
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

git:
  depth: 1



before_install:
  - ${TRAVIS_BUILD_DIR}/travis/before_install.sh

install:
  - ${TRAVIS_BUILD_DIR}/travis/install.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/travis/before_script.sh

script:
  - ${TRAVIS_BUILD_DIR}/travis/script.sh

after_success:
  - ${TRAVIS_BUILD_DIR}/travis/after_success.sh

deploy:

notifications:
  email: false

#notifications:
#    slack:
#        rooms:
#            - privatix:ntmw2wh4PAHoodqtMc95KFDt#dapp-tech
