language: node_js
sudo: required

node_js:
  - 10.13.0

os: linux
dist: xenial

env:
  global:

git:
  depth: 1

before_install:
  - openssl aes-256-cbc -K $encrypted_b77f5f8c0032_key -iv $encrypted_b77f5f8c0032_iv -in ./travis/atests/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - mv -fv ./travis/atests/ssh-config ~/.ssh/config
  - echo -e ">>> some magic"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
  - ssh stagevm@89.38.99.85 pwd
  #- ssh stagevm@89.38.99.85 'bash -s' < ./travis/atests/clear.sh

install:
  - /bin/bash ./travis/atests/deploy.sh;

#after_success:
# - /bin/bash ./travis/atests/deploy.sh;
  



